# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsu < Formula
  desc "It provides a convenient integration of AWS virtual MFA devices into commandline based workflows."
  homepage "https://github.com/kreuzwerker/awsu"
  version "2.3.3"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://there-is-no-release-yet-but-to-make-brew-not-fail-on-the-tap.com"
    end
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/awsu/releases/download/v2.3.3/awsu_2.3.3_Darwin_x86_64.tar.gz"
      sha256 "111c9c6934d4f745a82cf2ed04596487158df8648b28d0089aa99b815177668a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/awsu/releases/download/v2.3.3/awsu_2.3.3_Linux_x86_64.tar.gz"
      sha256 "e8cfec1e9bc05a81fe9f15dee15f0b51af97da60c79340bcb1574cee84b63753"
    end
  end

  def install
    bin.install "awsu"
  end
end
