# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envplate < Formula
  desc "Docker-friendly trivial templating for configuration files using environment keys."
  homepage "https://github.com/kreuzwerker/envplate"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kreuzwerker/envplate/releases/download/v1.0.2/envplate_1.0.2_Darwin_arm64.tar.gz"
      sha256 "83fd481a920c4d6093ff04bc4347fa85f2350ab71ad3f870217a07e63ad3dc50"

      def install
        bin.install "envplate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/envplate/releases/download/v1.0.2/envplate_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "730ce96fbd62c64cb025d9be510def2d619afe83f79fbd063d4374e6010af04e"

      def install
        bin.install "envplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kreuzwerker/envplate/releases/download/v1.0.2/envplate_1.0.2_Linux_arm64.tar.gz"
      sha256 "f8718f5982bd3466d19022c1d705a85820b9c1474614e2d0087305797a546bc9"

      def install
        bin.install "envplate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/envplate/releases/download/v1.0.2/envplate_1.0.2_Linux_x86_64.tar.gz"
      sha256 "59ad30aac04431848342b559264646bf9c0e5d48829d77e3c357bc60d01f1b1a"

      def install
        bin.install "envplate"
      end
    end
  end
end
