# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envplate < Formula
  desc "Docker-friendly trivial templating for configuration files using environment keys."
  homepage "https://github.com/kreuzwerker/envplate"
  version "1.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kreuzwerker/envplate/releases/download/v1.0.1/envplate_1.0.1_Darwin_arm64.tar.gz"
      sha256 "cd850678595eb26584201c46cbbaddd025f9532eabafe298c73d0b48957cfd92"
    end
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/envplate/releases/download/v1.0.1/envplate_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "bba41c614b10b841d228c39377989ddca7acc4824bea3783f1a396e995356e94"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kreuzwerker/envplate/releases/download/v1.0.1/envplate_1.0.1_Linux_arm64.tar.gz"
      sha256 "2ce7c50e12037a16ddc3fd792c582bb07c44aa6197885d83365af0cc44977e5a"
    end
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/envplate/releases/download/v1.0.1/envplate_1.0.1_Linux_x86_64.tar.gz"
      sha256 "29ef4142b76b676b009c6581fc0e7889f88d0846dc59e8a2c079ac6e96535905"
    end
  end

  def install
    bin.install "envplate"
  end
end
