# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envsec < Formula
  desc "Encrypted environment variables via AWS KMS."
  homepage "https://github.com/kreuzwerker/envsec"
  version "1.2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kreuzwerker/envsec/releases/download/v1.2.0/envsec_1.2.0_Darwin_arm64.tar.gz"
      sha256 "4654bea39fed2f3b6552a9658415279976a080e129c3de80a0f84411ca0c7750"
    end
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/envsec/releases/download/v1.2.0/envsec_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "7e726811db9ba3db23594b06a592482687d1a38596cf36e505a818ebf8695b18"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/envsec/releases/download/v1.2.0/envsec_1.2.0_Linux_x86_64.tar.gz"
      sha256 "d1c72cfd110994fbbe4047eedcdab04af34ab71aaeba0d30d9405ab98ecae463"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kreuzwerker/envsec/releases/download/v1.2.0/envsec_1.2.0_Linux_arm64.tar.gz"
      sha256 "a0ce041e407ac1ad2a36e084b5de9e826d15cea4528158c7bcf76bd384d109bd"
    end
  end

  def install
    bin.install "envsec"
  end
end
