# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envsec < Formula
  desc "Encrypted environment variables via AWS KMS."
  homepage "https://github.com/kreuzwerker/envsec"
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/envsec/releases/download/v1.2.2/envsec_1.2.2_Darwin_x86_64.tar.gz"
      sha256 "cf9d26c29fe9dcafb61099831d803effb477da04a0498e77cb7c819a907636b6"

      def install
        bin.install "envsec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kreuzwerker/envsec/releases/download/v1.2.2/envsec_1.2.2_Darwin_arm64.tar.gz"
      sha256 "1d945627e98497d5f6aa9f374d8f854e38338e447c382cc122ced076749a9bf0"

      def install
        bin.install "envsec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kreuzwerker/envsec/releases/download/v1.2.2/envsec_1.2.2_Linux_arm64.tar.gz"
      sha256 "8bf28d90994790c86709ca3542278441312b9921ab873e51c57a52dbd6e3a5ca"

      def install
        bin.install "envsec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/envsec/releases/download/v1.2.2/envsec_1.2.2_Linux_x86_64.tar.gz"
      sha256 "793a6800ebd17acccdea27667add53d3754bc46db8e2115e9a439140318577f7"

      def install
        bin.install "envsec"
      end
    end
  end
end
