# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class M1TerraformProviderHelper < Formula
  desc "CLI to support with downloading and compiling terraform providers for Mac with M1 chip."
  homepage "https://github.com/kreuzwerker/m1-terraform-provider-helper"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kreuzwerker/m1-terraform-provider-helper/releases/download/0.7.0/m1-terraform-provider-helper_0.7.0_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c7b9adf151f1c92aef5bc51769802205c049793035744827c98af17a8308a53f"

      def install
        bin.install "m1-terraform-provider-helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/m1-terraform-provider-helper/releases/download/0.7.0/m1-terraform-provider-helper_0.7.0_Darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a51cd636c4aad92b78685b8df13894eb85fb0b793e214a5db809caa029ba68f5"

      def install
        bin.install "m1-terraform-provider-helper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kreuzwerker/m1-terraform-provider-helper/releases/download/0.7.0/m1-terraform-provider-helper_0.7.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "dfa636a1562009ab74e02f407dcd83f1ca81087f9126cf5e1f7ab8046957f51a"

      def install
        bin.install "m1-terraform-provider-helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/m1-terraform-provider-helper/releases/download/0.7.0/m1-terraform-provider-helper_0.7.0_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c6224c4cb4accdd6f95a5fe718d8e9f3924a55f440eaa1bcd2239da49367140e"

      def install
        bin.install "m1-terraform-provider-helper"
      end
    end
  end

  depends_on "go"
end
