# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class M1TerraformProviderHelper < Formula
  desc "CLI to support with downloading and compiling terraform providers for Mac with M1 chip."
  homepage "https://github.com/kreuzwerker/m1-terraform-provider-helper"
  version "0.7.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kreuzwerker/m1-terraform-provider-helper/releases/download/0.7.3/m1-terraform-provider-helper_0.7.3_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "35145f7b44c89fe250d35d9da39bf89490282ab1798ef5d10b888d514be06e38"

      def install
        bin.install "m1-terraform-provider-helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/m1-terraform-provider-helper/releases/download/0.7.3/m1-terraform-provider-helper_0.7.3_Darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f2b49881b351b2207d6ae66a86e58a579441afe36f441485fe8e212d9271da23"

      def install
        bin.install "m1-terraform-provider-helper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kreuzwerker/m1-terraform-provider-helper/releases/download/0.7.3/m1-terraform-provider-helper_0.7.3_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c598bb32aec57bd6edfc1eff9df251830e16ff6b47f3045877479ff6875cfb9d"

      def install
        bin.install "m1-terraform-provider-helper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kreuzwerker/m1-terraform-provider-helper/releases/download/0.7.3/m1-terraform-provider-helper_0.7.3_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "999f6d884265fa8b3e06cc7323cfc55229531ae096f9fdeaa86cd03cae5f5262"

      def install
        bin.install "m1-terraform-provider-helper"
      end
    end
  end

  depends_on "go"
end
